version: 2
channels:
  - "conda-forge"
  - "nodefaults"
dependencies:
  - "jupyterlab>=4.4.2"
  - "jupyterlab-favorites"
  - "jupyter-collaboration"
  - "jupyter-server-proxy"
  - "jupyterlab-myst"
  - "jupyterlab-geojson"
  - "nbdime"

  # Python mainstays
  - "numpy"
  - "matplotlib"
  - "pandas"
  - "scipy"
  - "xarray"

  # geo
  - "jupytergis >=0.5.0"
  - "leafmap"
  - "folium"
  - "geopandas"
  - "gdal"
  - "geos"
  - "geotiff"
  - "h5netcdf"
  - "h5py"
  - "rasterio"
  - "shapely"

  # Publishing
  - "mystmd"
  - "typst"

  # Testing and validation
  - "ruff"

  # GitHub utilities
  - "gh"
  - "gh-scoped-creds"
