channels:
  - "conda-forge"
  - "nodefaults"
dependencies:
  - "python>=3.12"
  - "jupyterlab>=4.4.2"
  - "jupyterlab-favorites"
  - "jupyter-server-proxy"
  - "jupyterlab-myst"
  - "jupyterlab-geojson"
  - "nbdime"
  - "dask"
  - "boto3"
  - "s3fs"
  - "urllib3 ~=1.26.19"  # https://github.com/psf/requests/issues/6443

  # Python mainstays
  - "numpy"
  - "matplotlib"
  - "ipympl"
  - "hvplot"
  - "pandas"
  - "scipy"
  - "xarray"

  # geo
  - "jupytergis >=0.5.0"
  - "leafmap"
  - "folium"
  - "geopandas"
  - "gdal"
  - "geos"
  - "geotiff"
  - "h5netcdf"
  - "h5py"
  - "rasterio"
  - "rioxarray"
  - "cartopy"
  - "shapely"
  - "geoviews"
  - "pystac-client"
  - "intake-stac"
  - "intake-xarray <2"
  - "icepyx >=2.0.0"

  # Publishing
  - "mystmd"
  - "typst"

  # Testing and validation
  - "ruff"
  - "pre-commit"

  # GitHub utilities
  - "gh"
  - "gh-scoped-creds"
  - "pip"
  - pip:
    - "jupyter-collaboration==4.1.0rc0"
